services:
  - type: web
    name: rawgen-t43n
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: python server.py
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8000
